# Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
import numpy as np

# River Water Level 2021-2025

In [2]:
df_river_2021_2025=pd.read_csv(r"Datasets\\River Water Level\\TamilNadu_River_Water_Level_Hourly_Telemetry_2021-2025.csv")
df_river_2021_2025.head()

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,Data Acquisition Time,River Water Level Telemetry Hourly (meter)
0,1,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,25-07-2022 14:00,0.030
1,2,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,26-07-2022 04:00,0.005
2,3,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,26-07-2022 07:00,0.047
3,4,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,26-07-2022 08:00,0.029
4,5,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,26-07-2022 10:00,0.038

In [3]:
df_river_2021_2025.drop(columns=['Unnamed: 0'],inplace=True, errors='ignore')
df_river_2021_2025.rename(columns={'River Water Level Telemetry Hourly (meter)':'Hourly Water Level'},inplace=True)

In [4]:
df_river_2021_2025['Data Acquisition Time']=pd.to_datetime(df_river_2021_2025['Data Acquisition Time'],format='%d-%m-%Y %H:%M')
df_river_2021_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 72875 entries, 0 to 72874
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   SlNo                       72875 non-null  int64
 1   Station                    72875 non-null  str
 2   Agency                     72875 non-null  str
 3   State LGD Code             72875 non-null  int64
 4   State                      72875 non-null  str
 5   District LGD Code          72875 non-null  int64
 6   District                   72875 non-null  str
 7   Tehsil                     72875 non-null  str
 8   Block                      72875 non-null  str
 9   Village                    72875 non-null  str
 10  River                      72875 non-null  str
 11  Basin                      72875 non-null  str
 12  Tributary                  72875 non-null  str
 13  Subtributary               72875 non-null  str
 14  SubSubtributary            72875 non-null  str
 15  Local River                72875 non-null  str
 16  Latitude                   72875 non-null  float64
 17  Longitude                  72875 non-null  float64
 18  Is_DischargeDataAvailable  72875 non-null  str
 19  RL_of_zeroGauge            72875 non-null  int64
 20  MeanSeaLevel               72875 non-null  float64
 21  Data Acquisition Time      72875 non-null  datetime64[us]
 22  Hourly Water Level         72875 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(4), str(14)
memory usage: 12.8 MB

In [5]:
cols_to_drop = [
    'SlNo',
    'Agency',
    'State LGD Code',
    'State',
    'Basin',
    'Tributary',
    'Subtributary',
    'SubSubtributary',
    'Local River',
    'Is_DischargeDataAvailable',
    'RL_of_zeroGauge'
]

df_river_2021_2025.drop(columns=cols_to_drop, inplace=True, errors='ignore')
df_river_2021_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 72875 entries, 0 to 72874
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Station                72875 non-null  str
 1   District LGD Code      72875 non-null  int64
 2   District               72875 non-null  str
 3   Tehsil                 72875 non-null  str
 4   Block                  72875 non-null  str
 5   Village                72875 non-null  str
 6   River                  72875 non-null  str
 7   Latitude               72875 non-null  float64
 8   Longitude              72875 non-null  float64
 9   MeanSeaLevel           72875 non-null  float64
 10  Data Acquisition Time  72875 non-null  datetime64[us]
 11  Hourly Water Level     72875 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(1), str(6)
memory usage: 6.7 MB

# River Water Level 2026-2030

In [6]:
df_river_2026_2030=pd.read_csv(r"Datasets\\River Water Level\\TamilNadu_River_Water_Level_Hourly_Telemetry_2026-2030.csv")
df_river_2026_2030.head()

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,Data Acquisition Time,River Water Level Telemetry Hourly (meter)
0,1,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,04-01-2026 00:00,30.43
1,2,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,04-01-2026 01:00,30.43
2,3,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,04-01-2026 02:00,30.43
3,4,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,04-01-2026 03:00,30.43
4,5,Kamuthi Bridge,Tamil Nadu SW GW,33,Tamil Nadu,583,Ramanathapuram,KAMUTHI,-,-,...,-,-,Gundar,9.417222,78.368333,No,0,0.0,04-01-2026 04:00,30.43

In [7]:
df_river_2026_2030.drop(columns=['Is_DischargeDataAvailable','RL_of_zeroGauge','MeanSeaLevel','SlNo','Agency','State','State LGD Code','River','Basin','Tributary','Subtributary','SubSubtributary','Local River'],inplace=True)
df_river_2026_2030.rename(columns={'River Water Level Telemetry Hourly (meter)':'Hourly Water Level'},inplace=True)
df_river_2026_2030['Data Acquisition Time']=pd.to_datetime(df_river_2026_2030['Data Acquisition Time'],format='%d-%m-%Y %H:%M')
df_river_2026_2030.head()

,Station,District LGD Code,District,Tehsil,Block,Village,Latitude,Longitude,Data Acquisition Time,Hourly Water Level
0,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,9.417222,78.368333,2026-01-04 00:00:00,30.43
1,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,9.417222,78.368333,2026-01-04 01:00:00,30.43
2,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,9.417222,78.368333,2026-01-04 02:00:00,30.43
3,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,9.417222,78.368333,2026-01-04 03:00:00,30.43
4,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,9.417222,78.368333,2026-01-04 04:00:00,30.43

In [8]:
assert(df_river_2021_2025.columns.all() == df_river_2026_2030.columns.all())

In [9]:
df_river_2021_2025['Data Acquisition Time'].describe()

count                         72875
mean     2024-07-25 11:44:48.658662
min             2021-12-15 17:00:00
25%             2024-01-19 23:30:00
50%             2024-11-28 11:30:00
75%             2025-05-01 01:00:00
max             2025-12-31 23:00:00
Name: Data Acquisition Time, dtype: object

In [10]:
df_river_2026_2030['Data Acquisition Time'].describe()

count                          3310
mean     2026-02-06 20:22:11.238670
min             2026-01-01 00:00:00
25%             2026-01-17 00:00:00
50%             2026-02-03 04:30:00
75%             2026-02-20 09:45:00
max             2026-03-28 21:00:00
Name: Data Acquisition Time, dtype: object

# River Water 2021-2030

In [11]:
df_river_2021_2030 = pd.concat([df_river_2021_2025, df_river_2026_2030],ignore_index=True)
df_river_2021_2030.head()

,Station,District LGD Code,District,Tehsil,Block,Village,River,Latitude,Longitude,MeanSeaLevel,Data Acquisition Time,Hourly Water Level
0,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,Gundar,9.417222,78.368333,0.0,2022-07-25 14:00:00,0.030
1,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,Gundar,9.417222,78.368333,0.0,2022-07-26 04:00:00,0.005
2,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,Gundar,9.417222,78.368333,0.0,2022-07-26 07:00:00,0.047
3,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,Gundar,9.417222,78.368333,0.0,2022-07-26 08:00:00,0.029
4,Kamuthi Bridge,583,Ramanathapuram,KAMUTHI,-,-,Gundar,9.417222,78.368333,0.0,2022-07-26 10:00:00,0.038

In [12]:
df_river_2021_2030['Data Acquisition Time'].describe()

count                         76185
mean     2024-08-18 21:05:24.662335
min             2021-12-15 17:00:00
25%             2024-02-01 21:00:00
50%             2024-12-06 16:00:00
75%             2025-05-25 08:30:00
max             2026-03-28 21:00:00
Name: Data Acquisition Time, dtype: object

In [13]:
assert(df_river_2021_2030.shape[0] == df_river_2021_2025.shape[0]+df_river_2026_2030.shape[0])

In [14]:
df_river_2021_2030.sort_values(by=['Data Acquisition Time','District LGD Code'],inplace=True)

# River Discharge 2021-2025

In [15]:
df_discharge_2021_2025=pd.read_csv(r"Datasets/River Water Level/TamilNadu_River_Discharge_Hourly_Telemetry_2021-2025.csv")
df_discharge_2021_2025.head()

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,River,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Manual Daily River Water Discharge (m3/sec)
0,1,Rajapalayam,Tamil Nadu SW GW,33,Tamil Nadu,597,Virudhunagar,RAJAPALAYAM,-,-,Duplicate-Vaippar,East flowing rivers between Pennar and Kanyaku...,Arjunanadhi,-,-,Arjunanadhi,9.476944,77.558889,01-08-2011 08:00,43.400
1,2,Rajapalayam,Tamil Nadu SW GW,33,Tamil Nadu,597,Virudhunagar,RAJAPALAYAM,-,-,Duplicate-Vaippar,East flowing rivers between Pennar and Kanyaku...,Arjunanadhi,-,-,Arjunanadhi,9.476944,77.558889,02-08-2011 08:00,52.184
2,3,Rajapalayam,Tamil Nadu SW GW,33,Tamil Nadu,597,Virudhunagar,RAJAPALAYAM,-,-,Duplicate-Vaippar,East flowing rivers between Pennar and Kanyaku...,Arjunanadhi,-,-,Arjunanadhi,9.476944,77.558889,03-08-2011 08:00,53.902
3,4,Rajapalayam,Tamil Nadu SW GW,33,Tamil Nadu,597,Virudhunagar,RAJAPALAYAM,-,-,Duplicate-Vaippar,East flowing rivers between Pennar and Kanyaku...,Arjunanadhi,-,-,Arjunanadhi,9.476944,77.558889,04-08-2011 08:00,61.128
4,5,Rajapalayam,Tamil Nadu SW GW,33,Tamil Nadu,597,Virudhunagar,RAJAPALAYAM,-,-,Duplicate-Vaippar,East flowing rivers between Pennar and Kanyaku...,Arjunanadhi,-,-,Arjunanadhi,9.476944,77.558889,05-08-2011 08:00,55.419

In [16]:
df_discharge_2021_2025.drop(columns=['SlNo','Agency','State','State LGD Code','River','Basin','Tributary','Subtributary','SubSubtributary','Local River'],inplace=True)
df_discharge_2021_2025['Data Acquisition Time']=pd.to_datetime(df_discharge_2021_2025['Data Acquisition Time'],format='%d-%m-%Y %H:%M')
df_discharge_2021_2025.rename(columns={'Manual Daily River Water Discharge (m3/sec)':'Discharge Level'},inplace=True)
df_discharge_2021_2025.head()

,Station,District LGD Code,District,Tehsil,Block,Village,Latitude,Longitude,Data Acquisition Time,Discharge Level
0,Rajapalayam,597,Virudhunagar,RAJAPALAYAM,-,-,9.476944,77.558889,2011-08-01 08:00:00,43.400
1,Rajapalayam,597,Virudhunagar,RAJAPALAYAM,-,-,9.476944,77.558889,2011-08-02 08:00:00,52.184
2,Rajapalayam,597,Virudhunagar,RAJAPALAYAM,-,-,9.476944,77.558889,2011-08-03 08:00:00,53.902
3,Rajapalayam,597,Virudhunagar,RAJAPALAYAM,-,-,9.476944,77.558889,2011-08-04 08:00:00,61.128
4,Rajapalayam,597,Virudhunagar,RAJAPALAYAM,-,-,9.476944,77.558889,2011-08-05 08:00:00,55.419

# Final dataset

In [20]:
river = (
    df_river_2021_2030
    .groupby(['Data Acquisition Time', 'District LGD Code','District'])
    ['Hourly Water Level']
    .mean()
    .reset_index()
)
river.to_csv("river_data.csv", index=False)